BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ip" (
	"id"	INTEGER NOT NULL,
	"ip"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "poi" (
	"name"	TEXT NOT NULL UNIQUE,
	"description"	TEXT,
	"x"	REAL NOT NULL,
	"y"	REAL NOT NULL,
	"z"	REAL NOT NULL,
	PRIMARY KEY("name")
);
COMMIT;
